services:
  hive-bridge:
    image: mahdiyari/hive-bridge:0.0.3
    container_name: hive-bridge
    init: true
    tty: true
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - ENV_VAR=production
    restart: unless-stopped
